### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by joeblew99** [iqcouch/gocouch#1]
This is a very very good idea and relatively doable.

Boltdb runs on mobile and all desktops.

OT and CRDT algorithms in golang do exist.

There is no reason why the exact same code can exist on the client and server then.
On mobiles you just run it through gomobile. Then just wrap it into a iOS or android app. Personally I always build my GUI with gophers and polymer now.

There is also the replication aspects.

Also with boltdb there is an ORM. You can strong typing for free. 
CRDT operations can probably be expressed in this form easily I expect.

So there are lots of the bits in place.

Just wondering how far you have gotten and if we are thinking the same in terms of the design architecture that I briefly explained above ?

Cheers

**Comment by dragos-constantin-stoica** [comment]
Hello Joe,

This project is work in progress - and only a couple of CouchDB's APIs are implemented or partially implemented. The main goal is to have a native (compiled) application that runs on iOS and Android as a CouchDB server with the HTTP server active. Also we want to use this DB+Web Server combination as basis for distributing web applications by replication. A couchapp = Single Page web Application that is a series of attachments to a CouchDB document.

Your proposal is sound and I think it is more efficient than the actual HTTP overhead that CouchDB compatible systems implement (Cloudant, PouchDB, Coucbase etc). But this implies to have on the server side a sort of gateway between CoucdBD and mobile app, something like Sync Gateway from Couchbase. In my opinion your proposal should be followed in a forked or separated project and it is a good idea.

We will build the application as fully compatible with CouchDB replication algorithm as described [here](http://docs.couchdb.org/en/latest/replication/protocol.html#replication-protocol-algorithm). We do not intent to introduce another layer between mobile application and CouchDB server in this moment. We also luck time and money or both to finalize the development of the solution - eternal dilemma: code before you eat or eat before you code?

I hope in the next couple of months to find some spare time in order to finish a beta version. We need a lot of hands on the deck, if you know people that are interested we will more than happy to collaborate with them.

Cheers

**Comment by joeblew99** [comment]
Thanks for the heads up. It's a nice project.

In relation to the gateway aspects, am i using wstunnel as the gateway. It's in golang. But it's just a dumb matcher of persistent web sockets between the client and server.

The data sync server can be something else district from the proxy relay described above. It's only job is to allow peer 2 peer comms.
